### PR TITLE
API deprecated

### PR DESCRIPTION
**Pull request by ghost**
This Nami API implementation is deprecated soon. Please follow the API under the window.cardano.nami namespace. For more information check out CIP-30: https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030

### CODE REVIEW

**Comment by rgordon95** [comment]
this doesnt fix the problem just updates the readme..

**Comment by augustineashal** [comment]
it is working fine. the update is that the cardano object has to be used as window.cardano.selectedWallet instead of window.cardano

**Comment by gglucass** [comment]
I must be daft, but my window.cardano object does not have a selectedWallet method so this wouldn't work @augustineashal ?

**Comment by CyberCyclone** [comment]
Some other aspects have changed, such as `getRewardAddress` is now `getRewardAddresses`. This I know breaks the `delegate` function.

**Comment by CyberCyclone** [comment]
I've forked and working on fixing based on the CIP:30 changes that I know of relating to the delegate function: https://github.com/CyberCyclone/nami-wallet-api

**Pull request closed without merging**
